### ISSUE TITLE
remove packages not in cpanfile

### ISSUE THREAD

**Issue by bodyflex** [miyagawa/heroku-buildpack-perl#16]
would it be possible to modify the build script to remove all packages that are not present in the cpanfile file or to update all packages that don't specify a version to the latest version?

I had an issue where after adding a new package my entire app broke and even reversing the associated commits didn't help because the added package remained somewhere. the only thing that worked was a rollback. to be able to commit new changes, I had to manually go through all dependencies in the cpanfile and specify a version for all of them in order to have cpanm install the latest versions of the packages. took me also a good while to figure out what was going on.

**Comment by miyagawa** [comment]
This is the problem that Carton and Carmel are trying to solve, and why I'm working on a Docker-based approach to build Heroku slugs with Carmel https://github.com/miyagawa/perl-heroku-docker

**Comment by bodyflex** [comment]
alright. sounds good!
